# Generated by Django 3.2.6 on 2021-10-12 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last Name')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Adress')),
            ],
        ),
        migrations.AddField(
            model_name='cans',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user'),
        ),
    ]
